#docker-compose.yml
version: '2'
services:
    prometheus:
        build: ./prometheus
        volumes:
                - prometheus_data:/prometheus
        command:
                - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
                - '9090:9090'
        volumes:
                - prometheus_data:/prometheus
    grafana:
        image: grafana/grafana
        environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
        depends_on:
                - prometheus
        ports:
                - "3000:3000"
        volumes:
                - grafana_data:/var/lib/grafana
volumes:
        prometheus_data: {}
        grafana_data: {}
