# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'node'
      static_configs:
              - targets: ['localhost:9090','159.65.89.76:9100']
    - job_name: 'node2'
      static_configs:
              - targets : ['demo.do.prometheus.io:9100']
    - job_name: 'python'
      static_configs:
              - targets : ['159.65.89.76:8000']
